# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  apt_packages:
    # plantuml is required for sphinxcontrib.plantuml
    - plantuml

  tools:
    python: "3.14"

python:
  # See https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
  install:
    - method: uv
      command: sync
      groups:
        - docs

sphinx:
  configuration: docs/conf.py
